name: test

on:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis/redis-stack-server:6.2.6-v6
      srh:
        image: hiett/serverless-redis-http:latest
        env:
          SRH_MODE: env
          SRH_TOKEN: ${{ env.SRH_TOKEN }}
          SRH_CONNECTION_STRING: redis://redis:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci
        env:
          KV_REST_API_URL: http://srh:80
          KV_REST_API_TOKEN: ${{ env.SRH_TOKEN }}
          SERVICE_NAME=tiny-url
